In [1]:
import numpy as np
from scipy import sparse

a = sparse.random(100,100,format='csr',dtype='float64')

In [2]:
print(a)

  (0, 27)	0.8501931413700552
  (0, 43)	0.18537242139426535
  (0, 73)	0.04338877955085518
  (2, 12)	0.019286530361050547
  (2, 78)	0.7703555705538556
  (2, 93)	0.9484605818697074
  (5, 77)	0.807441539855188
  (6, 15)	0.8426434209703301
  (7, 7)	0.05594153764880505
  (7, 50)	0.9579347307513951
  (7, 57)	0.04467508811953469
  (9, 56)	0.8691303301572516
  (10, 41)	0.14024221426930705
  (13, 28)	0.30130597443705187
  (13, 64)	0.9012533159986423
  (14, 70)	0.09418020749847356
  (15, 20)	0.3340366694925144
  (17, 86)	0.28854336012842785
  (18, 8)	0.3722225456950964
  (19, 37)	0.30721987053326205
  (20, 74)	0.1832975650189338
  (21, 47)	0.9743822724927529
  (22, 20)	0.7521643972673713
  (22, 44)	0.7059415108301103
  (22, 48)	0.29767961587951797
  :	:
  (78, 39)	0.4744375961474152
  (78, 94)	0.4311558404561864
  (79, 87)	0.12445648090007577
  (81, 25)	0.0009928722805289114
  (81, 65)	0.4376993235666411
  (82, 32)	0.7780951334140924
  (82, 78)	0.9117336285961763
  (82, 94)	0.3963449903550442
  (

In [3]:
check = a.toarray()

In [67]:
np.max(check)

0.8940978788643864

In [68]:
print(check)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.89409788]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.

In [4]:
row_sum = check.sum(axis=1)
length = len(row_sum)
print(length)

100


In [5]:
n_result = check/row_sum.reshape(length,1)
print(n_result)

[[ 0.  0.  0. ...  0.  0.  0.]
 [nan nan nan ... nan nan nan]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [nan nan nan ... nan nan nan]
 [ 0.  0.  0. ...  0.  0.  0.]]


/home/ysahil/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/home/ysahil/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [6]:
np.max(n_result)

/home/ysahil/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


nan

In [8]:
np.max(check)

0.984703960636127

In [11]:
# np.nan_to_num(n_result)
where_are_NaNs = np.isnan(n_result)
n_result[where_are_NaNs] = 0
print(n_result)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [13]:
np.max(n_result)
print(n_result[99][15])

1.0


In [14]:
n_c_result = sparse.csr_matrix(n_result)

In [15]:
print(n_c_result)

  (0, 27)	0.787978793936494
  (0, 43)	0.17180747518611478
  (0, 73)	0.04021373087739128
  (2, 12)	0.011096312405520026
  (2, 78)	0.44321637506460165
  (2, 93)	0.5456873125298783
  (5, 77)	1.0
  (6, 15)	1.0
  (7, 7)	0.05284725894899188
  (7, 50)	0.9049487536446571
  (7, 57)	0.04220398740635103
  (9, 56)	1.0
  (10, 41)	1.0
  (13, 28)	0.2505539451014403
  (13, 64)	0.7494460548985599
  (14, 70)	1.0
  (15, 20)	1.0
  (17, 86)	1.0
  (18, 8)	1.0
  (19, 37)	1.0
  (20, 74)	1.0
  (21, 47)	1.0
  (22, 20)	0.4283919573295357
  (22, 44)	0.40206591362656546
  (22, 48)	0.16954212904389881
  :	:
  (78, 39)	0.5238969022641968
  (78, 94)	0.47610309773580317
  (79, 87)	1.0
  (81, 25)	0.0022632549425948864
  (81, 65)	0.9977367450574051
  (82, 32)	0.37297714657366615
  (82, 78)	0.4370362859577007
  (82, 94)	0.1899865674686332
  (83, 32)	0.5727901470231783
  (83, 52)	0.4272098529768217
  (86, 34)	0.10128209065538989
  (86, 73)	0.3505775248966808
  (86, 87)	0.4884729406042745
  (86, 88)	0.05966744384365489
  (